<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WeaponController extends Controller
{
    
    public $armi = [

        [
            'id' => 1,
            'nome' => "Fucile d'assalto",
            'tipo' => "Fucile d'assalto",
            'descrizione' => "Un fucile versatile adatto per combattimenti a media distanza. Usato da molte fazioni per il suo equilibrio tra danno e precisione.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/FucileD'assalto.png",
            'alt' => "Immagine del fucile d'assalto.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',

            
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 30,
                    'danno_strutture' => 30,
                    'cadenza_fuoco' => 5.5,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.75,
                    'immagine' => "Media/FuciliAssalto/FucileD'assalto.png",
                    'alt' => "Fucile d'assalto comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',


                    
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 31,
                    'danno_strutture' => 31,
                    'cadenza_fuoco' => 5.5,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.63,
                    'immagine' => "Media/FuciliAssalto/FucileD'assalto.png",
                    'alt' => "Fucile d'assalto non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                    
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 33,
                    'danno_strutture' => 33,
                    'cadenza_fuoco' => 5.5,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.5,
                    'immagine' => "Media/FuciliAssalto/FucileD'assalto.png",
                    'alt' => "Fucile d'assalto raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 35,
                    'danno_strutture' => 35,
                    'cadenza_fuoco' => 5.5,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.19,
                    'immagine' => "Media/FuciliAssalto/SCAR.png",
                    'alt' => "Fucile d'assalto epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',

                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 36,
                    'danno_strutture' => 36,
                    'cadenza_fuoco' => 5.5,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.25,
                    'immagine' => "Media/FuciliAssalto/SCAR.png",
                    'alt' => "Fucile d'assalto leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
            
                    
                ],
            ]
        ],
        [
            'id' => 2,
            'nome' => "Vampa Fucile",
            'tipo' => "Fucile d'assalto",
            'descrizione' => "Fucile versatile che premia i tiri di precisione e permette di esplodere a brevi raffiche.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/VampaFucile.png",
            'alt' => "Immagine del Vampa Fucile.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 27,
                    'danno_strutture' => 27,
                    'cadenza_fuoco' => 2.5,
                    'caricatore' => 20,
                    'tempo_ricarica' => 2.86,
                    'immagine' => "Media/FuciliAssalto/VampaFucile.png",
                    'alt' => "Vampa Fucile comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 29,
                    'danno_strutture' => 29,
                    'cadenza_fuoco' => 2.5,
                    'caricatore' => 20,
                    'tempo_ricarica' => 2.73,
                    'immagine' => "Media/FuciliAssalto/VampaFucile.png",
                    'alt' => "Vampa Fucile non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 30,
                    'danno_strutture' => 30,
                    'cadenza_fuoco' => 2.5,
                    'caricatore' => 20,
                    'tempo_ricarica' => 2.6,
                    'immagine' => "Media/FuciliAssalto/VampaFucile.png",
                    'alt' => "Vampa Fucile raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 32,
                    'danno_strutture' => 32,
                    'cadenza_fuoco' => 2.5,
                    'caricatore' => 20,
                    'tempo_ricarica' => 2.47,
                    'immagine' => "Media/FuciliAssalto/VampaFucile2.png",
                    'alt' => "Vampa Fucile epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 33,
                    'danno_strutture' => 33,
                    'cadenza_fuoco' => 2.5,
                    'caricatore' => 20,
                    'tempo_ricarica' => 2.34,
                    'immagine' => "Media/FuciliAssalto/VampaFucile2.png",
                    'alt' => "Vampa Fucile leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
            ]
        ],
        
        [
            'id' => 3,
            'nome' => "Fucile d'Assalto Pesante",
            'tipo' => "Fucile d'assalto",
            'descrizione' => "Un fucile d'assalto potente con colpi pesanti, ideale per eliminare bersagli corazzati e infliggere ingenti danni alle strutture. Compensa la bassa cadenza con un alto impatto per colpo.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
            'alt' => "Immagine del Fucile d'Assalto Pesante.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 29,
                    'danno_strutture' => 29,
                    'cadenza_fuoco' => 5,
                    'caricatore' => 28,
                    'tempo_ricarica' => 2.75,
                    'immagine' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
                    'alt' => "Fucile d'Assalto Pesante comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 30,
                    'danno_strutture' => 30,
                    'cadenza_fuoco' => 5,
                    'caricatore' => 28,
                    'tempo_ricarica' => 2.63,
                    'immagine' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
                    'alt' => "Fucile d'Assalto Pesante non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 32,
                    'danno_strutture' => 32,
                    'cadenza_fuoco' => 5,
                    'caricatore' => 28,
                    'tempo_ricarica' => 2.5,
                    'immagine' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
                    'alt' => "Fucile d'Assalto Pesante raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 34,
                    'danno_strutture' => 34,
                    'cadenza_fuoco' => 5,
                    'caricatore' => 28,
                    'tempo_ricarica' => 2.38,
                    'immagine' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
                    'alt' => "Fucile d'Assalto Pesante epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 35,
                    'danno_strutture' => 35,
                    'cadenza_fuoco' => 5,
                    'caricatore' => 28,
                    'tempo_ricarica' => 2.25,
                    'immagine' => "Media/FuciliAssalto/FucileAssaltoPesante.png",
                    'alt' => "Fucile d'Assalto Pesante leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
            ]
        ],
        [
            'id' => 4,
            'nome' => "Fucile da Fanteria",
            'tipo' => "Fucile a colpo singolo",
            'descrizione' => "Il fucile da fanteria ha una precisione del 100% quando si mira con il mirino e infligge danni ingenti, ma ha un caricatore limitato a 8 o 10 colpi e non è completamente automatico.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/FucileDaFanteria.png",
            'alt' => "Immagine del Fucile da Fanteria.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 36,
                    'danno_strutture' => 36,
                    'cadenza_fuoco' => 4,
                    'caricatore' => 8,
                    'tempo_ricarica' => 2.53,
                    'immagine' => "Media/FuciliAssalto/FucileDaFanteria.png",
                    'alt' => "Fucile da Fanteria comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 38,
                    'danno_strutture' => 38,
                    'cadenza_fuoco' => 4,
                    'caricatore' => 8,
                    'tempo_ricarica' => 2.42,
                    'immagine' => "Media/FuciliAssalto/FucileDaFanteria.png",
                    'alt' => "Fucile da Fanteria non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 40,
                    'danno_strutture' => 40,
                    'cadenza_fuoco' => 4,
                    'caricatore' => 8,
                    'tempo_ricarica' => 2.3,
                    'immagine' => "Media/FuciliAssalto/FucileDaFanteria.png",
                    'alt' => "Fucile da Fanteria raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 42,
                    'danno_strutture' => 42,
                    'cadenza_fuoco' => 4,
                    'caricatore' => 10,
                    'tempo_ricarica' => 2.19,
                    'immagine' => "Media/FuciliAssalto/FucileDaFanteria2.png",
                    'alt' => "Fucile da Fanteria epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 44,
                    'danno_strutture' => 44,
                    'cadenza_fuoco' => 4,
                    'caricatore' => 10,
                    'tempo_ricarica' => 2.07,
                    'immagine' => "Media/FuciliAssalto/FucileDaFanteria2.png",
                    'alt' => "Fucile da Fanteria leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
            ]
        ],
        [
            'id' => 5,
            'nome' => "Fucile d'assalto MK-Alpha",
            'tipo' => "Fucile d'assalto",
            'descrizione' => "Un fucile d'assalto moderno dotato di mirino integrato, pensato per colpire con precisione a media-lunga distanza. Offre un ottimo equilibrio tra cadenza di fuoco e controllo.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/FucileMKAlpha.png",
            'alt' => "Immagine del Fucile d'assalto MK-Alpha.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 22,
                    'danno_strutture' => 22,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 3.85,
                    'immagine' => "Media/FuciliAssalto/FucileMKAlpha.png",
                    'alt' => "Fucile d'assalto MK-Alpha comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 23,
                    'danno_strutture' => 23,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 3.68,
                    'immagine' => "Media/FuciliAssalto/FucileMKAlpha.png",
                    'alt' => "Fucile d'assalto MK-Alpha non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 24,
                    'danno_strutture' => 24,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 3.5,
                    'immagine' => "Media/FuciliAssalto/FucileMKAlpha.png",
                    'alt' => "Fucile d'assalto MK-Alpha raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 25,
                    'danno_strutture' => 25,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 3.33,
                    'immagine' => "Media/FuciliAssalto/FucileMKAlpha.png",
                    'alt' => "Fucile d'assalto MK-Alpha epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 26,
                    'danno_strutture' => 26,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 3.15,
                    'immagine' => "Media/FuciliAssalto/FucileMKAlpha.png",
                    'alt' => "Fucile d'assalto MK-Alpha leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
            ]
        ],
        [
            'id' => 6,
            'nome' => "Fucile d'assalto tattico",
            'tipo' => "Fucile d'assalto",
            'descrizione' => "Fucile d'assalto preciso e stabile, progettato per garantire un alto tasso di colpi a segno anche in situazioni ravvicinate. Ottimo per i combattimenti tattici.",
            'categoria' => 'Fucili',
            'img' => "Media/FuciliAssalto/FucileTattico.png",
            'alt' => "Immagine del Fucile d'assalto tattico.",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        
            'varianti' => [
                [
                    'rarità' => 'Comune',
                    'danno' => 20,
                    'danno_strutture' => 19,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.42,
                    'immagine' => "Media/FuciliAssalto/FucileTattico.png",
                    'alt' => "Fucile d'assalto tattico comune",
                    'img-stars' => 'Media/Stellette-comune.png',
                    'img-rarity' => 'Media/comune.png',
                    'img-bg-card' => '/Media/bg-card-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Non Comune',
                    'danno' => 21,
                    'danno_strutture' => 20,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.31,
                    'immagine' => "Media/FuciliAssalto/FucileTattico.png",
                    'alt' => "Fucile d'assalto tattico non comune",
                    'img-stars' => '/Media/Stellette-non-comuni.png',
                    'img-rarity' => 'Media/non-comune.png',
                    'img-bg-card' => '/Media/bg-card-non-comune.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Raro',
                    'danno' => 22,
                    'danno_strutture' => 21,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.2,
                    'immagine' => "Media/FuciliAssalto/FucileTattico.png",
                    'alt' => "Fucile d'assalto tattico raro",
                    'img-stars' => 'Media/Stellette-Raro.png',
                    'img-rarity' => 'Media/Raro.png',
                    'img-bg-card' => '/Media/bg-card-Raro.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Epico',
                    'danno' => 23,
                    'danno_strutture' => 22,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 2.09,
                    'immagine' => "Media/FuciliAssalto/FucileTattico2.png",
                    'alt' => "Fucile d'assalto tattico epico",
                    'img-stars' => 'Media/Stellette-Epico.png',
                    'img-rarity' => 'Media/Epico.png',
                    'img-bg-card' => '/Media/bg-card-Epico.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
                [
                    'rarità' => 'Leggendario',
                    'danno' => 24,
                    'danno_strutture' => 23,
                    'cadenza_fuoco' => 7,
                    'caricatore' => 30,
                    'tempo_ricarica' => 1.98,
                    'immagine' => "Media/FuciliAssalto/FucileTattico2.png",
                    'alt' => "Fucile d'assalto tattico leggendario",
                    'img-stars' => 'Media/Stellette-Leggendario.png',
                    'img-rarity' => 'Media/Leggendario.png',
                    'img-bg-card' => '/Media/bg-card-Leggendario.png',
                    'type-ammo' => 'Munizioni Medie',
                    'type-ammo-img' => '/Media/munizioni-medie.png',
                ],
            ]
        ],
        [
    'id' => 7,
    'nome' => "Fucile d'assalto Furia",
    'tipo' => "Fucile d'assalto",
    'descrizione' => "Fucile d'assalto potente e aggressivo, progettato per infliggere danni elevati rapidamente. Ottimo per situazioni di combattimento intenso e ravvicinato.",
    'categoria' => 'Fucili',
    'img' => "Media/FuciliAssalto/FucileFuria.png",
    'alt' => "Immagine del Fucile d'assalto Furia.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Medie',
    'type-ammo-img' => '/Media/munizioni-medie.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 22,
            'danno_strutture' => 20,
            'cadenza_fuoco' => 8,
            'caricatore' => 25,
            'tempo_ricarica' => 2.5,
            'immagine' => "Media/FuciliAssalto/FucileFuria.png",
            'alt' => "Fucile d'assalto Furia comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 23,
            'danno_strutture' => 21,
            'cadenza_fuoco' => 8,
            'caricatore' => 25,
            'tempo_ricarica' => 2.38,
            'immagine' => "Media/FuciliAssalto/FucileFuria.png",
            'alt' => "Fucile d'assalto Furia non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 24,
            'danno_strutture' => 22,
            'cadenza_fuoco' => 8,
            'caricatore' => 25,
            'tempo_ricarica' => 2.25,
            'immagine' => "Media/FuciliAssalto/FucileFuria.png",
            'alt' => "Fucile d'assalto Furia raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 25,
            'danno_strutture' => 23,
            'cadenza_fuoco' => 8,
            'caricatore' => 25,
            'tempo_ricarica' => 2.1,
            'immagine' => "Media/FuciliAssalto/FucileFuria.png",
            'alt' => "Fucile d'assalto Furia epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 26,
            'danno_strutture' => 24,
            'cadenza_fuoco' => 8,
            'caricatore' => 25,
            'tempo_ricarica' => 1.95,
            'immagine' => "Media/FuciliAssalto/FucileFuria.png",
            'alt' => "Fucile d'assalto Furia leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Medie',
            'type-ammo-img' => '/Media/munizioni-medie.png',
        ],
    ]
],
[
    'id' => 8,
    'nome' => "Fucile a impulsi",
    'tipo' => "Fucile a impulsi",
    'descrizione' => "Fucile a impulsi ad alta precisione, che spara raffiche energetiche concentrate per colpire bersagli a media distanza con grande efficacia.",
    'categoria' => 'Fucili',
    'img' => "Media/FuciliAssalto/FucileImpulsi.png",
    'alt' => "Immagine del Fucile a impulsi.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Energetiche',
    'type-ammo-img' => '/Media/munizioni-energetiche.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 18,
            'danno_strutture' => 16,
            'cadenza_fuoco' => 6,
            'caricatore' => 40,
            'tempo_ricarica' => 2.7,
            'immagine' => "Media/FuciliAssalto/FucileImpulsi.png",
            'alt' => "Fucile a impulsi comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Energetiche',
            'type-ammo-img' => '/Media/munizioni-energetiche.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 19,
            'danno_strutture' => 17,
            'cadenza_fuoco' => 6,
            'caricatore' => 40,
            'tempo_ricarica' => 2.58,
            'immagine' => "Media/FuciliAssalto/FucileImpulsi.png",
            'alt' => "Fucile a impulsi non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Energetiche',
            'type-ammo-img' => '/Media/munizioni-energetiche.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 20,
            'danno_strutture' => 18,
            'cadenza_fuoco' => 6,
            'caricatore' => 40,
            'tempo_ricarica' => 2.45,
            'immagine' => "Media/FuciliAssalto/FucileImpulsi.png",
            'alt' => "Fucile a impulsi raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Energetiche',
            'type-ammo-img' => '/Media/munizioni-energetiche.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 21,
            'danno_strutture' => 19,
            'cadenza_fuoco' => 6,
            'caricatore' => 40,
            'tempo_ricarica' => 2.3,
            'immagine' => "Media/FuciliAssalto/FucileImpulsi.png",
            'alt' => "Fucile a impulsi epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Energetiche',
            'type-ammo-img' => '/Media/munizioni-energetiche.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 22,
            'danno_strutture' => 20,
            'cadenza_fuoco' => 6,
            'caricatore' => 40,
            'tempo_ricarica' => 2.15,
            'immagine' => "Media/FuciliAssalto/FucileImpulsi.png",
            'alt' => "Fucile a impulsi leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Energetiche',
            'type-ammo-img' => '/Media/munizioni-energetiche.png',
        ],
    ]
],
[
    'id' => 9,
    'nome' => "Fucile da cecchino pesante",
    'tipo' => "Fucile da cecchino",
    'descrizione' => "Fucile da cecchino pesante, arma a lunga distanza con danno altissimo, ideale per eliminare bersagli singoli con precisione estrema. Ricarica lenta ma letale.",
    'categoria' => 'Fucili',
    'img' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
    'alt' => "Immagine del Fucile da cecchino pesante.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pesanti',
    'type-ammo-img' => '/Media/munizioni-pesanti.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 45,
            'danno_strutture' => 40,
            'cadenza_fuoco' => 1,
            'caricatore' => 5,
            'tempo_ricarica' => 4.5,
            'immagine' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
            'alt' => "Fucile da cecchino pesante comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 48,
            'danno_strutture' => 42,
            'cadenza_fuoco' => 1,
            'caricatore' => 5,
            'tempo_ricarica' => 4.3,
            'immagine' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
            'alt' => "Fucile da cecchino pesante non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 51,
            'danno_strutture' => 45,
            'cadenza_fuoco' => 1,
            'caricatore' => 5,
            'tempo_ricarica' => 4.1,
            'immagine' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
            'alt' => "Fucile da cecchino pesante raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 54,
            'danno_strutture' => 48,
            'cadenza_fuoco' => 1,
            'caricatore' => 5,
            'tempo_ricarica' => 3.9,
            'immagine' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
            'alt' => "Fucile da cecchino pesante epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 58,
            'danno_strutture' => 52,
            'cadenza_fuoco' => 1,
            'caricatore' => 5,
            'tempo_ricarica' => 3.7,
            'immagine' => "Media/FuciliCecchino/FucileCecchinoPesante.png",
            'alt' => "Fucile da cecchino pesante leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
    ]
],
[
    'id' => 10,
    'nome' => "Boom Cecchino",
    'tipo' => "Fucile da cecchino",
    'descrizione' => "Boom Cecchino: fucile da cecchino con elevato potere di penetrazione e danno esplosivo, ideale per eliminare gruppi di nemici o bersagli singoli con colpi precisi. Ricarica più veloce rispetto al fucile pesante.",
    'categoria' => 'Fucili',
    'img' => "Media/FuciliCecchino/BoomCecchino.png",
    'alt' => "Immagine del Boom Cecchino.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pesanti',
    'type-ammo-img' => '/Media/munizioni-pesanti.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 38,
            'danno_strutture' => 35,
            'cadenza_fuoco' => 1.5,
            'caricatore' => 6,
            'tempo_ricarica' => 3.8,
            'immagine' => "Media/FuciliCecchino/BoomCecchino.png",
            'alt' => "Boom Cecchino comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 40,
            'danno_strutture' => 37,
            'cadenza_fuoco' => 1.5,
            'caricatore' => 6,
            'tempo_ricarica' => 3.6,
            'immagine' => "Media/FuciliCecchino/BoomCecchino.png",
            'alt' => "Boom Cecchino non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 43,
            'danno_strutture' => 40,
            'cadenza_fuoco' => 1.5,
            'caricatore' => 6,
            'tempo_ricarica' => 3.4,
            'immagine' => "Media/FuciliCecchino/BoomCecchino.png",
            'alt' => "Boom Cecchino raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 46,
            'danno_strutture' => 43,
            'cadenza_fuoco' => 1.5,
            'caricatore' => 6,
            'tempo_ricarica' => 3.2,
            'immagine' => "Media/FuciliCecchino/BoomCecchino.png",
            'alt' => "Boom Cecchino epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 50,
            'danno_strutture' => 47,
            'cadenza_fuoco' => 1.5,
            'caricatore' => 6,
            'tempo_ricarica' => 3.0,
            'immagine' => "Media/FuciliCecchino/BoomCecchino.png",
            'alt' => "Boom Cecchino leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
    ]
],
[
    'id' => 11,
    'nome' => "Fucile da caccia",
    'tipo' => "Fucile da caccia",
    'descrizione' => "Fucile da caccia versatile e potente, eccellente per combattimenti a corto e medio raggio. Danno elevato ma cadenza di fuoco ridotta. Usa munizioni pesanti.",
    'categoria' => 'Fucili',
    'img' => "Media/FuciliCecchino/FucileDaCaccia.png",
    'alt' => "Immagine del Fucile da caccia.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pesanti',
    'type-ammo-img' => '/Media/munizioni-pesanti.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 30,
            'danno_strutture' => 28,
            'cadenza_fuoco' => 1.8,
            'caricatore' => 8,
            'tempo_ricarica' => 3.0,
            'immagine' => "Media/FuciliCecchino/FucileDaCaccia.png",
            'alt' => "Fucile da caccia comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 32,
            'danno_strutture' => 30,
            'cadenza_fuoco' => 1.8,
            'caricatore' => 8,
            'tempo_ricarica' => 2.85,
            'immagine' => "Media/FuciliCecchino/FucileDaCaccia.png",
            'alt' => "Fucile da caccia non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 34,
            'danno_strutture' => 32,
            'cadenza_fuoco' => 1.8,
            'caricatore' => 8,
            'tempo_ricarica' => 2.7,
            'immagine' => "Media/FuciliCecchino/FucileDaCaccia.png",
            'alt' => "Fucile da caccia raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 36,
            'danno_strutture' => 34,
            'cadenza_fuoco' => 1.8,
            'caricatore' => 8,
            'tempo_ricarica' => 2.55,
            'immagine' => "Media/FuciliCecchino/FucileDaCaccia.png",
            'alt' => "Fucile da caccia epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 39,
            'danno_strutture' => 37,
            'cadenza_fuoco' => 1.8,
            'caricatore' => 8,
            'tempo_ricarica' => 2.4,
            'immagine' => "Media/FuciliCecchino/FucileDaCaccia.png",
            'alt' => "Fucile da caccia leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pesanti',
            'type-ammo-img' => '/Media/munizioni-pesanti.png',
        ],
    ]
],
[
    'id' => 12,
    'nome' => "Mitraglietta compatta",
    'tipo' => "Mitraglietta",
    'descrizione' => "Mitraglietta compatta, veloce e maneggevole. Ottima per combattimenti ravvicinati grazie alla sua alta cadenza di fuoco e ricarica rapida. Usa munizioni leggere.",
    'categoria' => 'Mitragliette',
    'img' => "Media/Mitragliette/MitragliettaCompatta.png",
    'alt' => "Immagine della Mitraglietta compatta.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Leggere',
    'type-ammo-img' => '/Media/munizioni-leggere.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 12,
            'danno_strutture' => 10,
            'cadenza_fuoco' => 14,
            'caricatore' => 40,
            'tempo_ricarica' => 1.8,
            'immagine' => "Media/Mitragliette/MitragliettaCompatta.png",
            'alt' => "Mitraglietta compatta comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 13,
            'danno_strutture' => 11,
            'cadenza_fuoco' => 14,
            'caricatore' => 40,
            'tempo_ricarica' => 1.7,
            'immagine' => "Media/Mitragliette/MitragliettaCompatta.png",
            'alt' => "Mitraglietta compatta non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 14,
            'danno_strutture' => 12,
            'cadenza_fuoco' => 14,
            'caricatore' => 40,
            'tempo_ricarica' => 1.6,
            'immagine' => "Media/Mitragliette/MitragliettaCompatta.png",
            'alt' => "Mitraglietta compatta raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 15,
            'danno_strutture' => 13,
            'cadenza_fuoco' => 14,
            'caricatore' => 40,
            'tempo_ricarica' => 1.5,
            'immagine' => "Media/Mitragliette/MitragliettaCompatta.png",
            'alt' => "Mitraglietta compatta epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 16,
            'danno_strutture' => 14,
            'cadenza_fuoco' => 14,
            'caricatore' => 40,
            'tempo_ricarica' => 1.4,
            'immagine' => "Media/Mitragliette/MitragliettaCompatta.png",
            'alt' => "Mitraglietta compatta leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
    ]
],
[
    'id' => 13,
    'nome' => "Mitraglietta a raffica",
    'tipo' => "Mitraglietta",
    'descrizione' => "Mitraglietta a raffica, equilibrata tra precisione e velocità di fuoco. Ideale per combattimenti a medio raggio con munizioni leggere.",
    'categoria' => 'Mitragliette',
    'img' => "Media/Mitragliette/MitragliettaRaffica.png",
    'alt' => "Immagine della Mitraglietta a raffica.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Leggere',
    'type-ammo-img' => '/Media/munizioni-leggere.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 14,
            'danno_strutture' => 12,
            'cadenza_fuoco' => 10,
            'caricatore' => 35,
            'tempo_ricarica' => 1.9,
            'immagine' => "Media/Mitragliette/MitragliettaRaffica.png",
            'alt' => "Mitraglietta a raffica comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 15,
            'danno_strutture' => 13,
            'cadenza_fuoco' => 10,
            'caricatore' => 35,
            'tempo_ricarica' => 1.8,
            'immagine' => "Media/Mitragliette/MitragliettaRaffica.png",
            'alt' => "Mitraglietta a raffica non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 16,
            'danno_strutture' => 14,
            'cadenza_fuoco' => 10,
            'caricatore' => 35,
            'tempo_ricarica' => 1.7,
            'immagine' => "Media/Mitragliette/MitragliettaRaffica.png",
            'alt' => "Mitraglietta a raffica raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 17,
            'danno_strutture' => 15,
            'cadenza_fuoco' => 10,
            'caricatore' => 35,
            'tempo_ricarica' => 1.6,
            'immagine' => "Media/Mitragliette/MitragliettaRaffica.png",
            'alt' => "Mitraglietta a raffica epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 18,
            'danno_strutture' => 16,
            'cadenza_fuoco' => 10,
            'caricatore' => 35,
            'tempo_ricarica' => 1.5,
            'immagine' => "Media/Mitragliette/MitragliettaRaffica.png",
            'alt' => "Mitraglietta a raffica leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
    ]
],
[
    'id' => 14,
    'nome' => "Mitraglietta da combattimento",
    'tipo' => "Mitraglietta",
    'descrizione' => "Mitraglietta da combattimento, ottima per scontri ravvicinati e medi. Alta cadenza di fuoco e caricatore capiente con munizioni leggere.",
    'categoria' => 'Mitragliette',
    'img' => "Media/Mitragliette/MitragliettaCombattimento.png",
    'alt' => "Immagine della Mitraglietta da combattimento.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Leggere',
    'type-ammo-img' => '/Media/munizioni-leggere.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 15,
            'danno_strutture' => 13,
            'cadenza_fuoco' => 12,
            'caricatore' => 40,
            'tempo_ricarica' => 2.0,
            'immagine' => "Media/Mitragliette/MitragliettaCombattimento.png",
            'alt' => "Mitraglietta da combattimento comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 16,
            'danno_strutture' => 14,
            'cadenza_fuoco' => 12,
            'caricatore' => 40,
            'tempo_ricarica' => 1.9,
            'immagine' => "Media/Mitragliette/MitragliettaCombattimento.png",
            'alt' => "Mitraglietta da combattimento non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 17,
            'danno_strutture' => 15,
            'cadenza_fuoco' => 12,
            'caricatore' => 40,
            'tempo_ricarica' => 1.8,
            'immagine' => "Media/Mitragliette/MitragliettaCombattimento.png",
            'alt' => "Mitraglietta da combattimento raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 18,
            'danno_strutture' => 16,
            'cadenza_fuoco' => 12,
            'caricatore' => 40,
            'tempo_ricarica' => 1.7,
            'immagine' => "Media/Mitragliette/MitragliettaCombattimento.png",
            'alt' => "Mitraglietta da combattimento epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 19,
            'danno_strutture' => 17,
            'cadenza_fuoco' => 12,
            'caricatore' => 40,
            'tempo_ricarica' => 1.6,
            'immagine' => "Media/Mitragliette/MitragliettaCombattimento.png",
            'alt' => "Mitraglietta da combattimento leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
    ]
],
[
    'id' => 15,
    'nome' => "Mitraglietta Stinger",
    'tipo' => "Mitraglietta",
    'descrizione' => "Mitraglietta Stinger compatta, con altissima cadenza di fuoco e ottima maneggevolezza. Ideale per scontri ravvicinati con munizioni leggere.",
    'categoria' => 'Mitragliette',
    'img' => "Media/Mitragliette/MitragliettaStinger.png",
    'alt' => "Immagine della Mitraglietta Stinger.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Leggere',
    'type-ammo-img' => '/Media/munizioni-leggere.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 13,
            'danno_strutture' => 11,
            'cadenza_fuoco' => 15,
            'caricatore' => 35,
            'tempo_ricarica' => 2.1,
            'immagine' => "Media/Mitragliette/MitragliettaStinger.png",
            'alt' => "Mitraglietta Stinger comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 14,
            'danno_strutture' => 12,
            'cadenza_fuoco' => 15,
            'caricatore' => 35,
            'tempo_ricarica' => 1.95,
            'immagine' => "Media/Mitragliette/MitragliettaStinger.png",
            'alt' => "Mitraglietta Stinger non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 15,
            'danno_strutture' => 13,
            'cadenza_fuoco' => 15,
            'caricatore' => 35,
            'tempo_ricarica' => 1.8,
            'immagine' => "Media/Mitragliette/MitragliettaStinger.png",
            'alt' => "Mitraglietta Stinger raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Epico',
            'danno' => 16,
            'danno_strutture' => 14,
            'cadenza_fuoco' => 15,
            'caricatore' => 35,
            'tempo_ricarica' => 1.65,
            'immagine' => "Media/Mitragliette/MitragliettaStinger2.png",
            'alt' => "Mitraglietta Stinger epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 17,
            'danno_strutture' => 15,
            'cadenza_fuoco' => 15,
            'caricatore' => 35,
            'tempo_ricarica' => 1.5,
            'immagine' => "Media/Mitragliette/MitragliettaStinger2.png",
            'alt' => "Mitraglietta Stinger leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Leggere',
            'type-ammo-img' => '/Media/munizioni-leggere.png',
        ],
    ]
],
[
    'id' => 16,
    'nome' => "Fucile a pompa Spas",
    'tipo' => "Fucile a pompa",
    'descrizione' => "Fucile a pompa Spas potente con danno molto alto ma cadenza di fuoco più lenta. Ideale per colpi letali a distanza ravvicinata, usa munizioni pesanti.",
    'categoria' => 'Fucili a pompa',
    'img' => "Media/FuciliPompa/Spas.png",
    'alt' => "Immagine del fucile a pompa Spas.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pompa',
    'type-ammo-img' => '/Media/munizioni-pompa.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 80,
            'danno_strutture' => 70,
            'cadenza_fuoco' => 1.2,
            'caricatore' => 6,
            'tempo_ricarica' => 3.8,
            'immagine' => "Media/FuciliPompa/Spas.png",
            'alt' => "Fucile a pompa Spas comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',
            

        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 85,
            'danno_strutture' => 75,
            'cadenza_fuoco' => 1.2,
            'caricatore' => 6,
            'tempo_ricarica' => 3.6,
            'immagine' => "Media/FuciliPompa/Spas.png",
            'alt' => "Fucile a pompa Spas non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Raro',
            'danno' => 90,
            'danno_strutture' => 80,
            'cadenza_fuoco' => 1.2,
            'caricatore' => 6,
            'tempo_ricarica' => 3.4,
            'immagine' => "Media/FuciliPompa/Spas.png",
            'alt' => "Fucile a pompa Spas raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Epico',
            'danno' => 95,
            'danno_strutture' => 85,
            'cadenza_fuoco' => 1.2,
            'caricatore' => 6,
            'tempo_ricarica' => 3.2,
            'immagine' => "Media/FuciliPompa/Spas.png",
            'alt' => "Fucile a pompa Spas epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 100,
            'danno_strutture' => 90,
            'cadenza_fuoco' => 1.2,
            'caricatore' => 6,
            'tempo_ricarica' => 3,
            'immagine' => "Media/FuciliPompa/Spas.png",
            'alt' => "Fucile a pompa Spas leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
    ]
],
[
    'id' => 17,
    'nome' => "Fucile a pompa da combattimento",
    'tipo' => "Fucile a pompa",
    'descrizione' => "Fucile a pompa da combattimento con buona potenza, cadenza di fuoco elevata e ricarica rapida. Perfetto per scontri ravvicinati veloci.",
    'categoria' => 'Fucili a pompa',
    'img' => "Media/FuciliPompa/Combattimento.png",
    'alt' => "Immagine del fucile a pompa da combattimento.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pompa',
    'type-ammo-img' => '/Media/munizioni-pompa.png',
    


    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 60,
            'danno_strutture' => 55,
            'cadenza_fuoco' => 1.7,
            'caricatore' => 8,
            'tempo_ricarica' => 3.0,
            'immagine' => "Media/FuciliPompa/Combattimento.png",
            'alt' => "Fucile a pompa da combattimento comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 64,
            'danno_strutture' => 58,
            'cadenza_fuoco' => 1.7,
            'caricatore' => 8,
            'tempo_ricarica' => 2.85,
            'immagine' => "Media/FuciliPompa/Combattimento.png",
            'alt' => "Fucile a pompa da combattimento non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',
        ],
        [
            'rarità' => 'Raro',
            'danno' => 68,
            'danno_strutture' => 62,
            'cadenza_fuoco' => 1.7,
            'caricatore' => 8,
            'tempo_ricarica' => 2.7,
            'immagine' => "Media/FuciliPompa/Combattimento.png",
            'alt' => "Fucile a pompa da combattimento raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Epico',
            'danno' => 72,
            'danno_strutture' => 66,
            'cadenza_fuoco' => 1.7,
            'caricatore' => 8,
            'tempo_ricarica' => 2.55,
            'immagine' => "Media/FuciliPompa/Combattimento.png",
            'alt' => "Fucile a pompa da combattimento epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 76,
            'danno_strutture' => 70,
            'cadenza_fuoco' => 1.7,
            'caricatore' => 8,
            'tempo_ricarica' => 2.4,
            'immagine' => "Media/FuciliPompa/Combattimento.png",
            'alt' => "Fucile a pompa da combattimento leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
    ]
],
[
    'id' => 18,
    'nome' => "Pompa Viper",
    'tipo' => "Fucile a pompa",
    'descrizione' => "Pompa Viper: arma versatile che unisce un buon danno a una cadenza di fuoco sostenuta, ideale per combattimenti ravvicinati e dinamici.",
    'categoria' => 'Fucili a pompa',
    'img' => "Media/FuciliPompa/Viper.png",
    'alt' => "Immagine del fucile a pompa Viper.",
    'img-stars' => 'Media/Stellette-comune.png',
    'img-rarity' => 'Media/comune.png',
    'img-bg-card' => '/Media/bg-card-comune.png',
    'type-ammo' => 'Munizioni Pompa',
    'type-ammo-img' => '/Media/munizioni-pompa.png',

    'varianti' => [
        [
            'rarità' => 'Comune',
            'danno' => 55,
            'danno_strutture' => 50,
            'cadenza_fuoco' => 1.9,
            'caricatore' => 7,
            'tempo_ricarica' => 2.9,
            'immagine' => "Media/FuciliPompa/Viper.png",
            'alt' => "Pompa Viper comune",
            'img-stars' => 'Media/Stellette-comune.png',
            'img-rarity' => 'Media/comune.png',
            'img-bg-card' => '/Media/bg-card-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Non Comune',
            'danno' => 58,
            'danno_strutture' => 53,
            'cadenza_fuoco' => 1.9,
            'caricatore' => 7,
            'tempo_ricarica' => 2.75,
            'immagine' => "Media/FuciliPompa/Viper.png",
            'alt' => "Pompa Viper non comune",
            'img-stars' => '/Media/Stellette-non-comuni.png',
            'img-rarity' => 'Media/non-comune.png',
            'img-bg-card' => '/Media/bg-card-non-comune.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Raro',
            'danno' => 62,
            'danno_strutture' => 57,
            'cadenza_fuoco' => 1.9,
            'caricatore' => 7,
            'tempo_ricarica' => 2.6,
            'immagine' => "Media/FuciliPompa/Viper.png",
            'alt' => "Pompa Viper raro",
            'img-stars' => 'Media/Stellette-Raro.png',
            'img-rarity' => 'Media/Raro.png',
            'img-bg-card' => '/Media/bg-card-Raro.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Epico',
            'danno' => 66,
            'danno_strutture' => 61,
            'cadenza_fuoco' => 1.9,
            'caricatore' => 7,
            'tempo_ricarica' => 2.45,
            'immagine' => "Media/FuciliPompa/Viper.png",
            'alt' => "Pompa Viper epico",
            'img-stars' => 'Media/Stellette-Epico.png',
            'img-rarity' => 'Media/Epico.png',
            'img-bg-card' => '/Media/bg-card-Epico.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
        [
            'rarità' => 'Leggendario',
            'danno' => 70,
            'danno_strutture' => 65,
            'cadenza_fuoco' => 1.9,
            'caricatore' => 7,
            'tempo_ricarica' => 2.3,
            'immagine' => "Media/FuciliPompa/Viper.png",
            'alt' => "Pompa Viper leggendario",
            'img-stars' => 'Media/Stellette-Leggendario.png',
            'img-rarity' => 'Media/Leggendario.png',
            'img-bg-card' => '/Media/bg-card-Leggendario.png',
            'type-ammo' => 'Munizioni Pompa',
            'type-ammo-img' => '/Media/munizioni-pompa.png',

        ],
    ]
],












        
        

    ];


    public function WeaponFunction()
    {
        return view('armi', ['armi' => $this->armi]);
    }


public function DetailsWeaponFunction($id)
{
    foreach ($this->armi as $arma) {
        if ($arma['id'] == $id) {
            return view('DettaglioArmi', [
                'arma' => $arma,
                'maxDanno' => 50,
                'maxDannoStrutture' => 50,
                'maxCadenza' => 10,
                'maxCaricatore' => 50,
                'minTempoRicarica' => 1.5,
                'maxTempoRicarica' => 3,
            ]);
        }
    }

    // Se non troviamo l'arma, ritorniamo errore 404
    abort(404);
}

}
